# docker-compose.yml
# This is for WordPress and MySQL 5.7 Docker Container with upload Limit change

version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - univlinks_db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: UnivlinksRootPass
       MYSQL_DATABASE: univlinksdb
       MYSQL_USER: univlinksuser
       MYSQL_PASSWORD: UnivlinksPass

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: univlinksuser
       WORDPRESS_DB_PASSWORD: UnivlinksPass
       WORDPRESS_DB_NAME: univlinksdb
     volumes:
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
volumes:
    univlinks_db: {}
